# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 1.18

sudo: required
cache: packages

addons:
  apt:
    packages:
      - python2.7       # comment this to use python3
      #- python3        # uncomment this to use python3

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    
before_install:

  - sudo apt-get install r-base-dev
  - tlmgr install index  
  #------------------------------------- comment these lines to use python3
  - sudo apt-get install python-pip
  - sudo pip install --upgrade pip
  - sudo pip install fuzzywuzzy
  - sudo pip install python-Levenshtein
  #------------------------------------- uncomment these lines to use python3
  #- sudo apt-get install python3-pip
  #- sudo pip3 install --upgrade pip
  #- sudo pip3 install fuzzywuzzy
  #- sudo pip3 install python-Levenshtein
  #- sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  #- sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
  #-------------------------------------
  - sudo apt-get update

r_packages:
  - devtools
  - roxygen2
  - testthat
  - reticulate
  - R6
  - covr
  - knitr
  - rmarkdown
  
notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'
  
  
